// ============================================================
// SEED DATA
// ============================================================
// This file contains all the dummy/sample data for development.
// It provides realistic data for 6 Indian cities, 24 listings,
// sample reviews, and demo user accounts.
//
// This data is used when MongoDB is not connected, allowing
// the app to work fully without a database setup.
// ============================================================

const bcrypt = require('bcryptjs');

// ============================================================
// DEMO USERS
// ============================================================
const users = [
  {
    _id: 'user-admin-001',
    name: 'Admin User',
    email: 'admin@relocity.com',
    password: '$2a$10$xVqYLGcGm.pGBsGqR9pRiOdXhF5.vVrUDHKhx6g5r3Y4lXwAa.HYe', // admin123
    preferredCity: 'Mumbai',
    role: 'admin',
    favorites: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    _id: 'user-regular-001',
    name: 'Rahul Sharma',
    email: 'user@relocity.com',
    password: '$2a$10$xVqYLGcGm.pGBsGqR9pRiOdXhF5.vVrUDHKhx6g5r3Y4lXwAa.HYe', // user123
    preferredCity: 'Bangalore',
    role: 'user',
    favorites: ['listing-001', 'listing-005'],
    createdAt: new Date('2024-02-15'),
  },
  {
    _id: 'user-regular-002',
    name: 'Priya Patel',
    email: 'priya@example.com',
    password: '$2a$10$xVqYLGcGm.pGBsGqR9pRiOdXhF5.vVrUDHKhx6g5r3Y4lXwAa.HYe',
    preferredCity: 'Delhi',
    role: 'user',
    favorites: [],
    createdAt: new Date('2024-03-10'),
  },
];

// ============================================================
// CITIES
// ============================================================
const cities = [
  {
    _id: 'city-001',
    name: 'Mumbai',
    description: 'Mumbai, the City of Dreams, is India\'s financial capital and largest city. Known for its fast-paced lifestyle, Bollywood industry, and iconic landmarks like the Gateway of India. The city offers diverse career opportunities, world-class dining, and a vibrant nightlife scene.',
    image: '/images/mumbai.png',
    costOfLiving: {
      rent: 25000,
      food: 8000,
      transport: 3000,
      overall: 'High',
    },
    transport: ['Mumbai Metro', 'Local Trains', 'BEST Buses', 'Auto Rickshaws', 'Taxis', 'Ola/Uber'],
    famousAreas: [
      { name: 'Bandra', description: 'Trendy suburb with cafes, boutiques, and Bollywood celebrity homes.' },
      { name: 'Andheri', description: 'Major commercial hub with excellent connectivity and nightlife.' },
      { name: 'Powai', description: 'IT hub near IIT Bombay with modern apartments and lake views.' },
      { name: 'South Mumbai', description: 'Heritage area with colonial architecture, Marine Drive, and upscale living.' },
    ],
    hospitals: ['Lilavati Hospital', 'Kokilaben Hospital', 'Hinduja Hospital', 'Tata Memorial Hospital'],
    schools: ['Dhirubhai Ambani International School', 'Cathedral School', 'Podar International School'],
    lifestyle: 'Fast-paced metropolitan lifestyle with a blend of traditional and modern culture. Excellent street food, nightlife, and entertainment options.',
    population: '20.7 Million',
    createdAt: new Date('2024-01-01'),
  },
  {
    _id: 'city-002',
    name: 'Bangalore',
    description: 'Bangalore, the Silicon Valley of India, is the country\'s IT capital. Known for its pleasant weather year-round, thriving startup ecosystem, beautiful parks, and vibrant pub culture. A magnet for tech professionals from across the country.',
    image: '/images/bangalore.png',
    costOfLiving: {
      rent: 20000,
      food: 7000,
      transport: 2500,
      overall: 'Medium',
    },
    transport: ['Namma Metro', 'BMTC Buses', 'Auto Rickshaws', 'Ola/Uber', 'Rapido Bikes'],
    famousAreas: [
      { name: 'Koramangala', description: 'Startup hub with trendy restaurants, cafes, and co-working spaces.' },
      { name: 'Indiranagar', description: 'Upscale residential area famous for 100 Feet Road and nightlife.' },
      { name: 'Whitefield', description: 'Major IT corridor with tech parks and modern residential complexes.' },
      { name: 'HSR Layout', description: 'Popular with young professionals, known for its parks and eateries.' },
    ],
    hospitals: ['Manipal Hospital', 'Apollo Hospital', 'Narayana Health', 'Fortis Hospital'],
    schools: ['Bishop Cotton School', 'National Public School', 'Delhi Public School'],
    lifestyle: 'Laid-back yet dynamic tech culture. Great weather, craft beer scene, weekend getaways to Coorg and Mysore.',
    population: '12.3 Million',
    createdAt: new Date('2024-01-01'),
  },
  {
    _id: 'city-003',
    name: 'Delhi',
    description: 'Delhi, India\'s capital territory, is a historic city blending Mughal heritage with modern infrastructure. Home to iconic monuments, world-class metro system, diverse cuisine, and major political institutions. A hub for education, government, and commerce.',
    image: '/images/delhi.png',
    costOfLiving: {
      rent: 18000,
      food: 6000,
      transport: 2000,
      overall: 'Medium',
    },
    transport: ['Delhi Metro', 'DTC Buses', 'Auto Rickshaws', 'Cycle Rickshaws', 'Ola/Uber'],
    famousAreas: [
      { name: 'South Delhi', description: 'Upscale area with malls, premium restaurants, and green spaces.' },
      { name: 'Connaught Place', description: 'Iconic commercial center with colonial architecture and shopping.' },
      { name: 'Dwarka', description: 'Well-planned residential area with metro connectivity and modern amenities.' },
      { name: 'Noida', description: 'NCR satellite city with IT companies, malls, and affordable housing.' },
    ],
    hospitals: ['AIIMS', 'Max Hospital', 'Fortis Hospital', 'Apollo Hospital'],
    schools: ['Modern School', 'DPS RK Puram', 'Sanskriti School', 'Vasant Valley School'],
    lifestyle: 'Rich cultural heritage with street food paradise, historical monuments, and vibrant markets like Chandni Chowk.',
    population: '16.8 Million',
    createdAt: new Date('2024-01-01'),
  },
  {
    _id: 'city-004',
    name: 'Hyderabad',
    description: 'Hyderabad, the City of Pearls, perfectly blends old-world charm with modern tech growth. Known for its biryani, historic Charminar, booming IT sector in HITEC City, and relatively affordable cost of living. A top destination for IT professionals.',
    image: '/images/hyderabad.png',
    costOfLiving: {
      rent: 15000,
      food: 5500,
      transport: 2000,
      overall: 'Low',
    },
    transport: ['Hyderabad Metro', 'TSRTC Buses', 'Auto Rickshaws', 'Ola/Uber'],
    famousAreas: [
      { name: 'HITEC City', description: 'Major IT hub with tech parks, malls, and modern apartments.' },
      { name: 'Gachibowli', description: 'Growing IT corridor near Financial District with premium living.' },
      { name: 'Banjara Hills', description: 'Upscale area with restaurants, boutiques, and luxury living.' },
      { name: 'Jubilee Hills', description: 'Posh residential area popular with celebrities and business leaders.' },
    ],
    hospitals: ['Apollo Hospital', 'KIMS Hospital', 'Yashoda Hospital', 'AIG Hospital'],
    schools: ['Chirec International School', 'Oakridge International', 'Hyderabad Public School'],
    lifestyle: 'Relaxed pace of life with legendary Hyderabadi cuisine, historic sites, and a growing cosmopolitan culture.',
    population: '10.5 Million',
    createdAt: new Date('2024-01-01'),
  },
  {
    _id: 'city-005',
    name: 'Pune',
    description: 'Pune, the Oxford of the East, is known for its prestigious educational institutions, pleasant climate, and growing IT industry. A favorite among students and young professionals, offering a great balance of work and leisure at an affordable cost.',
    image: '/images/pune.png',
    costOfLiving: {
      rent: 14000,
      food: 5000,
      transport: 1800,
      overall: 'Low',
    },
    transport: ['Pune Metro', 'PMPML Buses', 'Auto Rickshaws', 'Ola/Uber'],
    famousAreas: [
      { name: 'Koregaon Park', description: 'Upscale area with cafes, bars, Osho Ashram, and expat community.' },
      { name: 'Hinjewadi', description: 'IT hub with Rajiv Gandhi Infotech Park and tech campuses.' },
      { name: 'Kothrud', description: 'Well-developed residential area with good schools and connectivity.' },
      { name: 'Viman Nagar', description: 'Modern area near airport with malls, restaurants, and apartments.' },
    ],
    hospitals: ['Ruby Hall Clinic', 'Sahyadri Hospital', 'KEM Hospital', 'Jehangir Hospital'],
    schools: ['Symbiosis International School', 'The Bishops School', 'DPS Pune'],
    lifestyle: 'Student-friendly city with a vibrant cultural scene, trekking spots nearby, and a growing cafe culture.',
    population: '7.4 Million',
    createdAt: new Date('2024-01-01'),
  },
  {
    _id: 'city-006',
    name: 'Chennai',
    description: 'Chennai, the Gateway to South India, is known for its rich cultural heritage, classical arts, beautiful beaches, and thriving automobile industry. The city offers a unique blend of tradition and modernity with a strong educational ecosystem.',
    image: '/images/chennai.png',
    costOfLiving: {
      rent: 16000,
      food: 5500,
      transport: 2000,
      overall: 'Medium',
    },
    transport: ['Chennai Metro', 'MTC Buses', 'Suburban Trains', 'Auto Rickshaws', 'Ola/Uber'],
    famousAreas: [
      { name: 'Adyar', description: 'Green residential area near the coast with IIT Madras nearby.' },
      { name: 'T. Nagar', description: 'Famous shopping district with traditional silk sarees and gold.' },
      { name: 'OMR (IT Corridor)', description: 'IT hub with tech parks, apartments, and modern infrastructure.' },
      { name: 'Anna Nagar', description: 'Well-planned residential area with parks, schools, and hospitals.' },
    ],
    hospitals: ['Apollo Hospital', 'MIOT Hospital', 'Fortis Malar Hospital', 'Sri Ramachandra Hospital'],
    schools: ['DAV School', 'Padma Seshadri School', 'Chettinad Vidyashram'],
    lifestyle: 'Traditional South Indian culture with classical music and dance festivals, Marina Beach walks, and filter coffee culture.',
    population: '10.9 Million',
    createdAt: new Date('2024-01-01'),
  },
];

// ============================================================
// LISTINGS
// ============================================================
const listings = [
  // --- HOUSING LISTINGS ---
  {
    _id: 'listing-001',
    title: 'Sunrise Luxury Apartments',
    category: 'housing',
    city: 'Mumbai',
    location: 'Bandra West, Mumbai',
    description: 'Modern 2BHK apartments with sea-facing balcony, gym, swimming pool, and 24/7 security. Close to Bandra station and Linking Road shopping area. Ideal for young professionals and families.',
    contact: { phone: '7272841234', email: 'sunrise@housing.com', website: 'https://sunrise-apts.com' },
    rating: 4.5,
    reviewCount: 12,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600',
    price: '₹35,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-15'),
  },
  {
    _id: 'listing-002',
    title: 'Green Valley PG Accommodation',
    category: 'housing',
    city: 'Bangalore',
    location: 'Koramangala 5th Block, Bangalore',
    description: 'Fully furnished PG with AC rooms, meals included, WiFi, laundry service, and housekeeping. Walking distance to major tech offices. Perfect for IT professionals new to Bangalore.',
    contact: { phone: '7272841234', email: 'greenvalley@pg.com', website: '' },
    rating: 4.2,
    reviewCount: 28,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600',
    price: '₹12,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-01'),
  },
  {
    _id: 'listing-003',
    title: 'Royal Residency Flats',
    category: 'housing',
    city: 'Delhi',
    location: 'Dwarka Sector 21, Delhi',
    description: '3BHK spacious flats with modular kitchen, parking, power backup, and park-facing views. Near metro station and schools. Great for families relocating to Delhi.',
    contact: { phone: '7272841234', email: 'royal@residency.com', website: 'https://royalresidency.in' },
    rating: 4.0,
    reviewCount: 15,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600',
    price: '₹22,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-20'),
  },
  {
    _id: 'listing-004',
    title: 'Cyber Towers Living',
    category: 'housing',
    city: 'Hyderabad',
    location: 'HITEC City, Hyderabad',
    description: 'Modern studio and 1BHK apartments near HITEC City tech parks. Fully furnished with gym, swimming pool, co-working space, and cafeteria. Ideal for IT professionals.',
    contact: { phone: '7272841234', email: 'cyber@towers.com', website: '' },
    rating: 4.3,
    reviewCount: 19,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600',
    price: '₹18,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-10'),
  },
  {
    _id: 'listing-005',
    title: 'Heritage Homes Pune',
    category: 'housing',
    city: 'Pune',
    location: 'Koregaon Park, Pune',
    description: 'Beautiful 2BHK apartments in the heart of Koregaon Park. Walking distance to cafes, restaurants, and Osho Ashram. Furnished with modern amenities and garden access.',
    contact: { phone: '7272841234', email: 'heritage@homes.com', website: '' },
    rating: 4.6,
    reviewCount: 22,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600',
    price: '₹16,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-15'),
  },
  {
    _id: 'listing-006',
    title: 'Marina Bay Apartments',
    category: 'housing',
    city: 'Chennai',
    location: 'Adyar, Chennai',
    description: 'Spacious 2BHK near Adyar Estuary with beach views. Close to IIT Madras and Besant Nagar beach. Gated community with swimming pool and children\'s play area.',
    contact: { phone: '7272841234', email: 'marina@apts.com', website: '' },
    rating: 4.1,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600',
    price: '₹20,000/month',
    verified: false,
    createdBy: 'admin',
    createdAt: new Date('2024-03-01'),
  },
  {
    _id: 'listing-007',
    title: 'Skyline Co-living Space',
    category: 'housing',
    city: 'Mumbai',
    location: 'Powai, Mumbai',
    description: 'Premium co-living space with private rooms, shared kitchen, gaming room, gym, and rooftop terrace. Community events every weekend. Near IIT Bombay and Hiranandani.',
    contact: { phone: '7272841234', email: 'skyline@coliving.com', website: 'https://skyline-coliving.com' },
    rating: 4.7,
    reviewCount: 35,
    image: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600',
    price: '₹15,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-25'),
  },
  {
    _id: 'listing-008',
    title: 'Whitefield Studio Homes',
    category: 'housing',
    city: 'Bangalore',
    location: 'Whitefield, Bangalore',
    description: 'Compact fully-furnished studio apartments perfect for single professionals. Walking distance to ITPL and major tech campuses. Includes WiFi, gym, and laundry.',
    contact: { phone: '7272841234', email: 'whitefield@studios.com', website: '' },
    rating: 3.9,
    reviewCount: 14,
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600',
    price: '₹10,000/month',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-03-05'),
  },

  // --- SCHOOL LISTINGS ---
  {
    _id: 'listing-009',
    title: 'Delhi Public School - Bangalore',
    category: 'school',
    city: 'Bangalore',
    location: 'Sarjapur Road, Bangalore',
    description: 'CBSE affiliated school with state-of-the-art campus, smart classrooms, sports facilities, and experienced faculty. Offers classes from Nursery to Grade 12. Known for academic excellence and holistic development.',
    contact: { phone: '7272841234', email: 'admission@dpsbangalore.com', website: 'https://dpsbangalore.com' },
    rating: 4.4,
    reviewCount: 45,
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600',
    price: '₹1,50,000/year',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-10'),
  },
  {
    _id: 'listing-010',
    title: 'Ryan International School',
    category: 'school',
    city: 'Mumbai',
    location: 'Kandivali, Mumbai',
    description: 'ICSE board school with modern infrastructure, computer labs, science labs, library, and sports grounds. Strong focus on academics, sports, and extracurricular activities.',
    contact: { phone: '7272841234', email: 'info@ryanmumbai.com', website: 'https://ryanmumbai.com' },
    rating: 4.1,
    reviewCount: 32,
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600',
    price: '₹1,20,000/year',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-12'),
  },
  {
    _id: 'listing-011',
    title: 'Oakridge International School',
    category: 'school',
    city: 'Hyderabad',
    location: 'Gachibowli, Hyderabad',
    description: 'IB World School offering international curriculum with global exposure. State-of-the-art campus with swimming pool, robotics lab, performing arts center, and sports academy.',
    contact: { phone: '7272841234', email: 'admissions@oakridge.in', website: 'https://oakridge.in' },
    rating: 4.6,
    reviewCount: 38,
    image: 'https://images.unsplash.com/photo-1613896527026-f195d5c818ed?w=600',
    price: '₹3,00,000/year',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-15'),
  },
  {
    _id: 'listing-012',
    title: 'Symbiosis International School',
    category: 'school',
    city: 'Pune',
    location: 'Viman Nagar, Pune',
    description: 'Progressive IB school known for innovative teaching methods, international exchange programs, and focus on environmental awareness. Beautiful green campus with modern facilities.',
    contact: { phone: '7272841234', email: 'info@symbiosis-school.com', website: 'https://symbiosis-school.com' },
    rating: 4.5,
    reviewCount: 29,
    image: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?w=600',
    price: '₹2,00,000/year',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-01'),
  },
  {
    _id: 'listing-013',
    title: 'Modern Public School',
    category: 'school',
    city: 'Delhi',
    location: 'Shalimar Bagh, Delhi',
    description: 'CBSE affiliated school with 30+ years of excellence. Air-conditioned classrooms, digital learning, sports academy for cricket and basketball, and strong alumni network.',
    contact: { phone: '7272841234', email: 'office@modernpublic.com', website: '' },
    rating: 4.0,
    reviewCount: 55,
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600',
    price: '₹90,000/year',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-18'),
  },
  {
    _id: 'listing-014',
    title: 'Chettinad Vidyashram',
    category: 'school',
    city: 'Chennai',
    location: 'RA Puram, Chennai',
    description: 'One of Chennai\'s top CBSE schools known for academic rigor and cultural programs. Sprawling campus with auditorium, labs, and sports facilities. Strong Bharatanatyam and music programs.',
    contact: { phone: '7272841234', email: 'info@chettinad.edu', website: '' },
    rating: 4.3,
    reviewCount: 41,
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600',
    price: '₹1,10,000/year',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-10'),
  },

  // --- HOSPITAL LISTINGS ---
  {
    _id: 'listing-015',
    title: 'Apollo Hospital',
    category: 'hospital',
    city: 'Chennai',
    location: 'Greams Road, Chennai',
    description: 'India\'s leading multi-specialty hospital with world-class healthcare services. 60+ specialties including cardiology, oncology, orthopedics, and neurology. International patient services available.',
    contact: { phone: '7272841234', email: 'info@apollochennai.com', website: 'https://apollohospitals.com' },
    rating: 4.7,
    reviewCount: 120,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600',
    price: 'Consultation: ₹800-2000',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-05'),
  },
  {
    _id: 'listing-016',
    title: 'Manipal Hospital',
    category: 'hospital',
    city: 'Bangalore',
    location: 'HAL Airport Road, Bangalore',
    description: 'Premier multi-specialty hospital with 600+ beds. Known for organ transplants, cardiac care, and robotic surgery. 24/7 emergency services and pharmacy. Cashless insurance accepted.',
    contact: { phone: '7272841234', email: 'info@manipalhospital.com', website: 'https://manipalhospitals.com' },
    rating: 4.5,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600',
    price: 'Consultation: ₹600-1500',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-08'),
  },
  {
    _id: 'listing-017',
    title: 'Kokilaben Dhirubhai Ambani Hospital',
    category: 'hospital',
    city: 'Mumbai',
    location: 'Andheri West, Mumbai',
    description: 'State-of-the-art hospital with advanced medical technology. Specializes in cancer treatment, cardiac surgery, neurosurgery, and bone marrow transplants. Beautiful healing environment with patient-centric care.',
    contact: { phone: '7272841234', email: 'info@kokilabenhospital.com', website: 'https://kokilabenhospital.com' },
    rating: 4.8,
    reviewCount: 95,
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600',
    price: 'Consultation: ₹1000-2500',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-10'),
  },
  {
    _id: 'listing-018',
    title: 'AIIMS Delhi',
    category: 'hospital',
    city: 'Delhi',
    location: 'Ansari Nagar, Delhi',
    description: 'India\'s premier government hospital and medical research institute. Offers affordable world-class healthcare across all specialties. Known for cutting-edge research and free/subsidized treatment.',
    contact: { phone: '7272841234', email: 'info@aiims.edu', website: 'https://aiims.edu' },
    rating: 4.4,
    reviewCount: 200,
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=600',
    price: 'Consultation: ₹10-250',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-03'),
  },
  {
    _id: 'listing-019',
    title: 'KIMS Hospital',
    category: 'hospital',
    city: 'Hyderabad',
    location: 'Secunderabad, Hyderabad',
    description: 'Multi-specialty hospital with 1000+ beds and 40+ specialties. Known for cardiac sciences, gastroenterology, and joint replacements. Modern ICU with 24/7 critical care team.',
    contact: { phone: '7272841234', email: 'info@kimshospitals.com', website: 'https://kimshospitals.com' },
    rating: 4.3,
    reviewCount: 67,
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=600',
    price: 'Consultation: ₹500-1200',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-12'),
  },
  {
    _id: 'listing-020',
    title: 'Ruby Hall Clinic',
    category: 'hospital',
    city: 'Pune',
    location: 'Sassoon Road, Pune',
    description: 'Pune\'s oldest and most trusted multi-specialty hospital. 550+ beds with specialties in cardiac care, orthopedics, and neonatal care. Known for compassionate patient care and skilled doctors.',
    contact: { phone: '7272841234', email: 'info@rubyhall.com', website: 'https://rubyhall.com' },
    rating: 4.2,
    reviewCount: 78,
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600',
    price: 'Consultation: ₹500-1000',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-15'),
  },
  {
    _id: 'listing-021',
    title: 'Lilavati Hospital',
    category: 'hospital',
    city: 'Mumbai',
    location: 'Bandra West, Mumbai',
    description: 'Premium multi-specialty hospital trusted by Bollywood celebrities. Excellence in cosmetic surgery, cardiology, orthopedics, and IVF. Beautiful sea-facing building with VIP suites.',
    contact: { phone: '7272841234', email: 'info@lilavatihospital.com', website: '' },
    rating: 4.6,
    reviewCount: 85,
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600',
    price: 'Consultation: ₹1000-2000',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-01'),
  },
  {
    _id: 'listing-022',
    title: 'Narayana Health City',
    category: 'hospital',
    city: 'Bangalore',
    location: 'Bommasandra, Bangalore',
    description: 'Affordable world-class hospital founded by Dr. Devi Shetty. Largest heart hospital in the world. Known for making quality healthcare accessible to all income levels.',
    contact: { phone: '7272841234', email: 'info@narayanahealth.org', website: 'https://narayanahealth.org' },
    rating: 4.5,
    reviewCount: 110,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600',
    price: 'Consultation: ₹300-800',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-01-20'),
  },
  {
    _id: 'listing-023',
    title: 'Fortis Memorial Research Institute',
    category: 'hospital',
    city: 'Delhi',
    location: 'Gurgaon, NCR',
    description: 'Next-generation hospital with cutting-edge technology including robotic surgery, CyberKnife, and PET-CT. 1000+ beds with international patient services and translation support.',
    contact: { phone: '7272841234', email: 'info@fortis.com', website: 'https://fortishealthcare.com' },
    rating: 4.4,
    reviewCount: 73,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600',
    price: 'Consultation: ₹800-2000',
    verified: true,
    createdBy: 'admin',
    createdAt: new Date('2024-02-05'),
  },
  {
    _id: 'listing-024',
    title: 'Sahyadri Hospital',
    category: 'hospital',
    city: 'Pune',
    location: 'Deccan Gymkhana, Pune',
    description: 'Trusted multi-specialty hospital chain in Pune with 5 centers. Known for cardiology, joint replacement, and maternity care. Affordable pricing with cashless insurance.',
    contact: { phone: '7272841234', email: 'info@sahyadri.in', website: 'https://sahyadri.in' },
    rating: 4.1,
    reviewCount: 56,
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=600',
    price: 'Consultation: ₹400-900',
    verified: false,
    createdBy: 'admin',
    createdAt: new Date('2024-02-10'),
  },
];

// ============================================================
// REVIEWS
// ============================================================
const reviews = [
  {
    _id: 'review-001',
    userName: 'Rahul Sharma',
    userId: 'user-regular-001',
    listingId: 'listing-001',
    rating: 5,
    comment: 'Amazing apartments! The sea-facing balcony is absolutely stunning. Great connectivity to Bandra station. Highly recommended for anyone moving to Mumbai.',
    createdAt: new Date('2024-03-15'),
  },
  {
    _id: 'review-002',
    userName: 'Priya Patel',
    userId: 'user-regular-002',
    listingId: 'listing-001',
    rating: 4,
    comment: 'Good apartments with nice amenities. The gym and pool are well-maintained. Only downside is the parking can be tight during weekends.',
    createdAt: new Date('2024-03-20'),
  },
  {
    _id: 'review-003',
    userName: 'Amit Kumar',
    userId: 'user-regular-003',
    listingId: 'listing-002',
    rating: 4,
    comment: 'Great PG for IT professionals! Food is decent, WiFi is reliable, and the location in Koramangala is perfect. Walking distance to many startups.',
    createdAt: new Date('2024-04-01'),
  },
  {
    _id: 'review-004',
    userName: 'Sneha Reddy',
    userId: 'user-regular-004',
    listingId: 'listing-009',
    rating: 5,
    comment: 'Excellent school! My children have thrived here. The teachers are dedicated and the facilities are top-notch. The sports program is outstanding.',
    createdAt: new Date('2024-02-10'),
  },
  {
    _id: 'review-005',
    userName: 'Vikram Singh',
    userId: 'user-regular-005',
    listingId: 'listing-015',
    rating: 5,
    comment: 'World-class healthcare. The cardiology department saved my father\'s life. Professional staff, clean facilities, and transparent billing. The best hospital in Chennai.',
    createdAt: new Date('2024-03-05'),
  },
  {
    _id: 'review-006',
    userName: 'Meera Joshi',
    userId: 'user-regular-006',
    listingId: 'listing-005',
    rating: 5,
    comment: 'Beautiful apartment in the best area of Pune! The Koregaon Park location is unbeatable. So many great restaurants and cafes nearby. Lovely experience.',
    createdAt: new Date('2024-04-15'),
  },
  {
    _id: 'review-007',
    userName: 'Arjun Nair',
    userId: 'user-regular-007',
    listingId: 'listing-016',
    rating: 4,
    comment: 'Good hospital with competent doctors. Emergency response was quick when we needed it. Slightly expensive but worth it for the quality of care.',
    createdAt: new Date('2024-03-25'),
  },
  {
    _id: 'review-008',
    userName: 'Deepa Menon',
    userId: 'user-regular-008',
    listingId: 'listing-004',
    rating: 4,
    comment: 'Perfect location for IT professionals working in HITEC City. The co-working space in the building is a great bonus. Maintenance could be better though.',
    createdAt: new Date('2024-04-05'),
  },
  {
    _id: 'review-009',
    userName: 'Raj Malhotra',
    userId: 'user-regular-009',
    listingId: 'listing-011',
    rating: 5,
    comment: 'IB curriculum is excellent for global exposure. My daughter learned so much about international perspectives. The robotics lab is incredible!',
    createdAt: new Date('2024-02-28'),
  },
  {
    _id: 'review-010',
    userName: 'Anita Desai',
    userId: 'user-regular-010',
    listingId: 'listing-017',
    rating: 5,
    comment: 'Premium hospital with cutting-edge technology. The cancer treatment department is among the best in India. Staff is professional and caring.',
    createdAt: new Date('2024-03-18'),
  },
  {
    _id: 'review-011',
    userName: 'Karan Gupta',
    userId: 'user-regular-011',
    listingId: 'listing-007',
    rating: 4,
    comment: 'Love the co-living concept! Weekend events are fun and great for networking. The rooftop terrace has amazing views of Powai lake.',
    createdAt: new Date('2024-04-10'),
  },
  {
    _id: 'review-012',
    userName: 'Pooja Agarwal',
    userId: 'user-regular-012',
    listingId: 'listing-003',
    rating: 4,
    comment: 'Decent apartments in Dwarka. Metro is right next door which is super convenient. The park view from 3rd floor is beautiful. Good value for money.',
    createdAt: new Date('2024-03-28'),
  },
  {
    _id: 'review-013',
    userName: 'Suresh Iyer',
    userId: 'user-regular-013',
    listingId: 'listing-018',
    rating: 4,
    comment: 'The best government hospital in India. Waiting times can be long but the quality of treatment is excellent and very affordable. True service to the nation.',
    createdAt: new Date('2024-02-20'),
  },
  {
    _id: 'review-014',
    userName: 'Nisha Kapoor',
    userId: 'user-regular-014',
    listingId: 'listing-012',
    rating: 5,
    comment: 'Outstanding IB school with innovative teaching methods. The environmental awareness programs are unique. My son loves going to school every day!',
    createdAt: new Date('2024-04-20'),
  },
  {
    _id: 'review-015',
    userName: 'Ravi Teja',
    userId: 'user-regular-015',
    listingId: 'listing-022',
    rating: 5,
    comment: 'Dr. Devi Shetty\'s vision of affordable healthcare is truly realized here. World-class cardiac care at a fraction of private hospital costs. Highly recommended.',
    createdAt: new Date('2024-03-12'),
  },
];

module.exports = { users, cities, listings, reviews };
